### ISSUE TITLE
Hide tabs on change group

### ISSUE THREAD

**Issue by PGBastien** [Rapptz/power-tabs#1]
In setting of the extension i checked "Hide tabs on group change"
On click to one group (in menu bar) other tabs are not hidden, it's only the focus that changes.

Thanks :)

Env : Linux Ubuntu 17.10 (64 bits)
FF version : Firefox For Developers 59.0b3 (64 bits)

**Comment by Rapptz** [comment]
Are you sure you have `extensions.webextensions.tabhide.enabled` set to `true` in `about:config`?

**Comment by Rapptz** [comment]
Going to assume that comment fixed it. Going to close now. 👍
