### ISSUE TITLE
Tab Group doesn't save over multiple windows

### ISSUE THREAD

**Issue by ghost** [Rapptz/power-tabs#10]
[This is the issue](https://imgur.com/a/olqW4). When used over multiple windows the same group has two contents. How should the program "remember" tab groups over multiple windows?

**Comment by Rapptz** [comment]
This is how I purposefully designed it. Window IDs change so I didn't want something finnicky to be attached to an ID that changes.

Considering I rarely use multiple windows though I'm open to suggestions on how to redesign it.
